name: Metadata Parsers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Requirements
        run: |
          sudo apt install -y dirmngr gnupg apt-transport-https ca-certificates software-properties-common
          sudo apt install -y wget curl
          R -e "install.packages('yaml',dependencies=TRUE, repos='http://cran.rstudio.com/')"
          R -e "install.packages('desc',dependencies=TRUE, repos='http://cran.rstudio.com/')"
          R -e "install.packages('optparse',dependencies=TRUE, repos='http://cran.rstudio.com/')"
          python -m pip install pyyaml toml mock pytest
      - name: Run Tests
        run: pytest -s
      - name: Test Action on Python
        uses: kzscisoft/cff-creation-action@testing
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_path: test
          branch: testing
          language: python
          force: true
          prefix: python
      - name: Test Action on Julia
        uses: kzscisoft/cff-creation-action@testing
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_path: test
          branch: testing
          language: Julia
          prefix: julia
          force: true
      - name: Test Action on R
        uses: kzscisoft/cff-creation-action@testing
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          project_path: test
          branch: testing
          language: R